volumes:
  wordpress:
    #name: wordpress
    driver: local
    driver_opts:
      device: /home/j/data/WordPress
      o: bind
      type: none
  mariadb:
    #name: mariadb
    driver: local
    driver_opts:
      device: /home/j/data/DB
      o: bind
      type: none

networks:
  Inception:
    name: Inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx42
    volumes:
      - wordpress:/var/www/html
    networks:
      - Inception
    ports:
      - "443:443" #443: navigateur    :4242 port d entre
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress42
    volumes:
      - wordpress:/var/www/html
    networks:
      - Inception
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb42
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - Inception
    restart: no

#prochaines etapes
#->creer un volume pour wp 
#->mettre un fichier html dedans
#->sen servir avec nginx
#changement de port 443 apres certificat ssl
#->Makefile pour clean et exec le up --build