volumes:
  wordpress:
    #name: wordpress
    driver: local
    driver_opts:
      device: /home/j/data/WordPress
      o: bind
      type: none
  mariadb:
    #name: mariadb
    driver: local
    driver_opts:
      device: /home/j/data/DB
      o: bind
      type: none

networks:
  Inception:
    name: Inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx42
    ports:
      - "42:4242" #42: navigateur    :4242 port d entre
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress42
    volumes:
      - wordpress:/var/www/html
    restart: always

#prochaines etapes
#->creer un volume pour wp 
#->mettre un fichier html dedans
#->sen servir avec nginx
#changement de port 443 apres certificat ssl
#->Makefile pour clean et exec le up --build