version: "3.7"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/j/Documents/Inception/wordpress
      o: bind
      type: none

services:
  nginx:
    build: ./requirements/nginx

    container_name: nginx
    ports:
      - "42:80" #80: navigateur    :80 port d entre
    restart: always

#prochaines etapes
#->creer un volume pour wp 
#->mettre un fichier html dedans
#->sen servir avec nginx
#changement de port 443 apres certificat ssl
#->Makefile pour clean et exec le up --build